add32.o: add32.cc add32.h common.h ../../include/streamflowc.h
addgeneric.o: addgeneric.cc
sum8.o: sum8.cc
system.o: system.cc system.h common.h ../../include/streamflowc.h sum8.h \
  add.h addgeneric.h add32.h tb.h
tb.o: tb.cc tb.h common.h ../../include/streamflowc.h
main.o: main.cc system.h common.h ../../include/streamflowc.h
